site_name: CCR
site_url: https://github.com/quinlan-lab/ccr
repo_url: https://github.com/quinlan-lab/ccr
pages:
- Home: index.md
- Examples:
    - gnomAD: examples/gnomad.md
    - New Versions: examples/updates.md
theme: cinder
